name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/configure-pages@v5
      
      # Seus passos de build aqui
      - run: echo "Build commands here..."
      
      # Use UPLOAD-PAGES-ARTIFACT (não upload-artifact)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Ou @v3 se disponível
        with:
          path: ./dist  # Ajuste para o diretório de saída do seu build
      
      - name: Deploy
        uses: actions/deploy-pages@v3
